document.addEventListener('DOMContentLoaded', function () {
  const horoscopes = {
      aries: [
        "Hari ini adalah hari yang baik untuk mengejar impian Anda dengan semangat penuh.",
        "Anda akan menemukan energi baru yang membantu Anda menyelesaikan tugas-tugas yang tertunda.",
        "Jadikan hari ini sebagai kesempatan untuk membangun hubungan yang lebih dekat dengan orang-orang terdekat Anda.",
        "Keberanian Anda akan diuji hari ini, tetapi Anda akan menemukan kekuatan di dalam diri sendiri untuk mengatasinya.",
        "Jangan ragu untuk mengambil risiko dalam mencapai tujuan Anda. Keberuntungan berada di pihak Anda.",
        "Jika ada konflik, selesaikan dengan kepala dingin dan jangan biarkan emosi menguasai.",
        "Sikap optimis Anda akan memberikan energi positif kepada orang di sekitar Anda.",
        "Anda memiliki kemampuan untuk memotivasi orang lain. Gunakan kekuatan ini dengan bijak.",
        "Fokuslah pada hal-hal yang dapat Anda kendalikan dan biarkan yang lain berjalan dengan alaminya.",
        "Cobalah untuk menemukan waktu untuk bersantai dan merenung hari ini.",
        "Jangan terlalu keras pada diri sendiri. Terimalah kelebihan dan kekurangan Anda dengan penuh kasih.",
        "Anda memiliki potensi besar. Percayalah pada diri sendiri dan teruslah berusaha.",
        "Berkomitmenlah untuk terus belajar dan berkembang secara pribadi dan profesional.",
        "Perhatikan detail dan jangan abaikan hal-hal kecil yang penting.",
        "Kejujuran adalah pondasi yang kuat untuk membangun hubungan yang langgeng.",
        "Tetap tenang dan teruskan langkah Anda meskipun menghadapi rintangan.",
        "Manfaatkan intuisi Anda dalam mengambil keputusan penting hari ini.",
        "Luangkan waktu untuk bersantai dan mengisi ulang energi.",
        "Jangan ragu untuk mengekspresikan ide-ide kreatif Anda secara terbuka.",
        "Berikan diri Anda penghargaan yang pantas atas pencapaian Anda.",
      ],
      taurus: [
        "Fokuslah pada tugas-tugas praktis dan biarkan hasil kerja keras Anda berbicara untuk dirinya sendiri.",
        "Anda akan menemukan kepuasan dalam mencapai tujuan finansial yang telah Anda tetapkan.",
        "Hari ini adalah waktu yang baik untuk merenungkan nilai-nilai Anda dan mengubah hal-hal yang tidak sesuai.",
        "Jangan terlalu keras pada diri sendiri. Terimalah kelebihan dan kekurangan Anda dengan penuh kasih.",
        "Konsentrasi pada keseimbangan hidup dan kerja akan memberikan hasil yang baik.",
        "Jangan ragu untuk mencari dukungan dari orang-orang terdekat Anda saat menghadapi tantangan.",
        "Perhatikan kebutuhan fisik Anda dan pastikan untuk memberikan diri Anda istirahat yang cukup.",
        "Anda memiliki kemampuan untuk mempertahankan kestabilan emosi dalam situasi sulit.",
        "Jangan ragu untuk mengambil risiko yang dihitung dalam mencapai tujuan besar Anda.",
        "Jadikan hari ini sebagai kesempatan untuk berterima kasih pada orang-orang yang telah memberikan dukungan kepada Anda.",
        "Konsentrasi pada detil akan membantu Anda mencapai hasil yang lebih baik dalam pekerjaan Anda.",
        "Gunakan kekuatan Anda untuk mempengaruhi perubahan positif di sekitar Anda.",
        "Jangan ragu untuk mengungkapkan perasaan Anda secara jujur dan terbuka kepada orang yang Anda percayai.",
        "Kejujuran adalah pondasi yang kuat untuk membangun hubungan yang langgeng.",
        "Anda memiliki bakat untuk menginspirasi orang lain. Gunakan kekuatan ini dengan bijak.",
        "Jadikan waktu untuk menikmati hobi atau aktivitas yang memberikan kepuasan pribadi.",
        "Luangkan waktu untuk merencanakan tujuan jangka panjang Anda secara sistematis dan dengan hati-hati.",
        "Tetap fokus pada tujuan Anda dan jangan terlalu terganggu oleh hal-hal yang tidak perlu.",
        "Jangan ragu untuk mengejar peluang baru yang mungkin muncul hari ini.",
        "Perhatikan perasaan Anda dan ekspresikan mereka dengan jujur kepada orang lain.",
      ],
      gemini: [
        "Jaga komunikasi terbuka dengan semua orang di sekitar Anda. Anda akan menemukan inspirasi dari percakapan.",
        "Cari tahu lebih banyak tentang minat dan hobi baru yang dapat membantu Anda berkembang secara pribadi.",
        "Anda memiliki kecerdasan dan kreativitas yang luar biasa. Gunakan mereka untuk mencapai tujuan Anda.",
        "Hari ini adalah hari yang baik untuk menjelajahi berbagai pilihan dan mengambil keputusan yang berani.",
        "Jangan ragu untuk mengekspresikan ide-ide kreatif Anda secara terbuka.",
        "Anda memiliki kemampuan untuk memotivasi orang lain. Gunakan kekuatan ini dengan bijak.",
        "Tetap tenang dan teruskan langkah Anda meskipun menghadapi rintangan.",
        "Berikan diri Anda penghargaan yang pantas atas pencapaian Anda.",
        "Jangan ragu untuk mengejar peluang baru yang mungkin muncul hari ini.",
        "Anda memiliki potensi besar. Percayalah pada diri sendiri dan teruslah berusaha.",
        "Berkomitmenlah untuk terus belajar dan berkembang secara pribadi dan profesional.",
        "Perhatikan detail dan jangan abaikan hal-hal kecil yang penting.",
        "Kejujuran adalah pondasi yang kuat untuk membangun hubungan yang langgeng.",
        "Manfaatkan intuisi Anda dalam mengambil keputusan penting hari ini.",
        "Luangkan waktu untuk bersantai dan mengisi ulang energi.",
        "Jika ada konflik, selesaikan dengan kepala dingin dan jangan biarkan emosi menguasai.",
        "Sikap optimis Anda akan memberikan energi positif kepada orang di sekitar Anda.",
        "Anda memiliki kemampuan untuk mempengaruhi perubahan positif di sekitar Anda.",
        "Fokuslah pada hal-hal yang dapat Anda kendalikan dan biarkan yang lain berjalan dengan alaminya.",
        "Cobalah untuk menemukan waktu untuk bersantai dan merenung hari ini.",
      ],
      cancer: [
        "Jaga kesehatan fisik dan emosional Anda dengan baik hari ini. Perhatikan pola makan dan istirahat yang cukup.",
        "Bersikaplah lembut pada diri sendiri dan orang lain. Kehangatan Anda akan memberi inspirasi pada orang-orang di sekitar Anda.",
        "Kejujuran adalah kunci untuk membangun hubungan yang kokoh. Berbicaralah dari hati.",
        "Anda memiliki intuisi yang kuat. Percayalah pada insting Anda ketika menghadapi keputusan sulit.",
        "Jangan ragu untuk mengekspresikan perasaan Anda secara terbuka kepada orang-orang yang Anda percayai.",
        "Luangkan waktu untuk merenung dan mengevaluasi tujuan hidup Anda hari ini.",
        "Anda memiliki kemampuan untuk memberikan dukungan emosional yang besar pada orang-orang terdekat Anda.",
        "Jangan ragu untuk meminta bantuan atau nasihat dari orang yang Anda percayai saat menghadapi kesulitan.",
        "Jadikan hari ini sebagai kesempatan untuk memaafkan dan melupakan masa lalu yang menyakitkan.",
        "Kesabaran adalah kunci untuk mengatasi tantangan hari ini.",
        "Jangan biarkan emosi negatif menguasai Anda. Cari cara untuk menenangkan pikiran Anda.",
        "Anda memiliki potensi besar. Percayalah pada diri sendiri dan teruslah berusaha.",
        "Berkomitmenlah untuk terus belajar dan berkembang secara pribadi dan profesional.",
        "Perhatikan detail dan jangan abaikan hal-hal kecil yang penting.",
        "Kejujuran adalah pondasi yang kuat untuk membangun hubungan yang langgeng.",
        "Tetap tenang dan teruskan langkah Anda meskipun menghadapi rintangan.",
        "Manfaatkan intuisi Anda dalam mengambil keputusan penting hari ini.",
        "Luangkan waktu untuk bersantai dan mengisi ulang energi.",
        "Jangan ragu untuk mengekspresikan ide-ide kreatif Anda secara terbuka.",
        "Berikan diri Anda penghargaan yang pantas atas pencapaian Anda.",
      ],
      leo: [
        "Hari ini adalah waktu yang baik untuk menonjolkan bakat dan kemampuan Anda. Jangan ragu untuk menunjukkan keahlian Anda.",
        "Jaga rasa percaya diri Anda tetap tinggi. Ini adalah kunci untuk menarik peluang baru.",
        "Anda memiliki kemampuan untuk mempengaruhi orang lain. Gunakan kekuatan ini dengan bijak.",
        "Jangan ragu untuk mengejar peluang baru yang mungkin muncul hari ini.",
        "Anda memiliki potensi besar. Percayalah pada diri sendiri dan teruslah berusaha.",
        "Berkomitmenlah untuk terus belajar dan berkembang secara pribadi dan profesional.",
        "Perhatikan detail dan jangan abaikan hal-hal kecil yang penting.",
        "Kejujuran adalah pondasi yang kuat untuk membangun hubungan yang langgeng.",
        "Manfaatkan intuisi Anda dalam mengambil keputusan penting hari ini.",
        "Luangkan waktu untuk bersantai dan mengisi ulang energi.",
        "Jika ada konflik, selesaikan dengan kepala dingin dan jangan biarkan emosi menguasai.",
        "Sikap optimis Anda akan memberikan energi positif kepada orang di sekitar Anda.",
        "Anda memiliki kemampuan untuk mempengaruhi perubahan positif di sekitar Anda.",
        "Fokuslah pada hal-hal yang dapat Anda kendalikan dan biarkan yang lain berjalan dengan alaminya.",
        "Cobalah untuk menemukan waktu untuk bersantai dan merenung hari ini.",
        "Jangan terlalu keras pada diri sendiri. Terimalah kelebihan dan kekurangan Anda dengan penuh kasih.",
        "Anda memiliki potensi besar. Percayalah pada diri sendiri dan teruslah berusaha.",
        "Berkomitmenlah untuk terus belajar dan berkembang secara pribadi dan profesional.",   
        "Luangkan waktu untuk merencanakan tujuan jangka panjang Anda secara sistematis dan dengan hati-hati.",
        "Tetap fokus pada tujuan Anda dan jangan terlalu terganggu oleh hal-hal yang tidak perlu.",
        "Jangan ragu untuk mengejar peluang baru yang mungkin muncul hari ini.",
        "Perhatikan perasaan Anda dan ekspresikan mereka dengan jujur kepada orang lain.",
        "Anda memiliki potensi besar. Percayalah pada diri sendiri dan teruslah berusaha.",
        "Berkomitmenlah untuk terus belajar dan berkembang secara pribadi dan profesional.",
        "Perhatikan detail dan jangan abaikan hal-hal kecil yang penting.",
        "Kejujuran adalah pondasi yang kuat untuk membangun hubungan yang langgeng.",
        "Manfaatkan intuisi Anda dalam mengambil keputusan penting hari ini.",
        "Luangkan waktu untuk bersantai dan mengisi ulang energi.",
      ],
      capricorn: [
        "Jaga fokus pada tujuan jangka panjang Anda. Ketekunan dan disiplin adalah kunci kesuksesan.",
        "Anda memiliki kemampuan untuk mencapai hasil yang luar biasa melalui kerja keras dan dedikasi.",
        "Hari ini adalah waktu yang baik untuk merencanakan langkah-langkah konkret menuju pencapaian impian Anda.",
        "Jangan ragu untuk mencari nasihat dari mentor atau orang yang Anda percayai.",
        "Perhatikan kebutuhan fisik Anda dan pastikan untuk memberikan diri Anda istirahat yang cukup.",
        "Anda memiliki kemampuan untuk mempertahankan kestabilan emosi dalam situasi sulit.",
        "Jangan ragu untuk mengambil risiko yang dihitung dalam mencapai tujuan besar Anda.",
        "Jadikan hari ini sebagai kesempatan untuk berterima kasih pada orang-orang yang telah memberikan dukungan kepada Anda.",
        "Konsentrasi pada detil akan membantu Anda mencapai hasil yang lebih baik dalam pekerjaan Anda.",
        "Gunakan kekuatan Anda untuk mempengaruhi perubahan positif di sekitar Anda.",
        "Jangan ragu untuk mengungkapkan perasaan Anda secara jujur dan terbuka kepada orang yang Anda percayai.",
        "Kejujuran adalah pondasi yang kuat untuk membangun hubungan yang langgeng.",
        "Anda memiliki bakat untuk menginspirasi orang lain. Gunakan kekuatan ini dengan bijak.",
        "Jadikan waktu untuk menikmati hobi atau aktivitas yang memberikan kepuasan pribadi.",
        "Luangkan waktu untuk merencanakan tujuan jangka panjang Anda secara sistematis dan dengan hati-hati.",
        "Tetap fokus pada tujuan Anda dan jangan terlalu terganggu oleh hal-hal yang tidak perlu.",
        "Jangan ragu untuk mengejar peluang baru yang mungkin muncul hari ini.",
        "Perhatikan perasaan Anda dan ekspresikan mereka dengan jujur kepada orang lain.",
        "Anda memiliki potensi besar. Percayalah pada diri sendiri dan teruslah berusaha.",
        "Berkomitmenlah untuk terus belajar dan berkembang secara pribadi dan profesional.",
      ],
      aquarius: [
        "Hari ini adalah waktu yang baik untuk mengeksplorasi ide-ide inovatif dan berpikir di luar kotak.",
        "Jaga komunikasi terbuka dengan semua orang di sekitar Anda. Anda akan menemukan inspirasi dari percakapan.",
        "Anda memiliki kecerdasan dan kreativitas yang luar biasa. Gunakan mereka untuk mencapai tujuan Anda.",
        "Hari ini adalah hari yang baik untuk menjelajahi berbagai pilihan dan mengambil keputusan yang berani.",
        "Jangan ragu untuk mengekspresikan ide-ide kreatif Anda secara terbuka.",
        "Anda memiliki kemampuan untuk memotivasi orang lain. Gunakan kekuatan ini dengan bijak.",
        "Tetap tenang dan teruskan langkah Anda meskipun menghadapi rintangan.",
        "Berikan diri Anda penghargaan yang pantas atas pencapaian Anda.",
        "Jangan ragu untuk mengejar peluang baru yang mungkin muncul hari ini.",
        "Anda memiliki potensi besar. Percayalah pada diri sendiri dan teruslah berusaha.",
        "Berkomitmenlah untuk terus belajar dan berkembang secara pribadi dan profesional.",
        "Perhatikan detail dan jangan abaikan hal-hal kecil yang penting.",
        "Kejujuran adalah pondasi yang kuat untuk membangun hubungan yang langgeng.",
        "Manfaatkan intuisi Anda dalam mengambil keputusan penting hari ini.",
        "Luangkan waktu untuk bersantai dan mengisi ulang energi.",
        "Jika ada konflik, selesaikan dengan kepala dingin dan jangan biarkan emosi menguasai.",
        "Sikap optimis Anda akan memberikan energi positif kepada orang di sekitar Anda.",
        "Anda memiliki kemampuan untuk mempengaruhi perubahan positif di sekitar Anda.",
        "Fokuslah pada hal-hal yang dapat Anda kendalikan dan biarkan yang lain berjalan dengan alaminya.",
        "Cobalah untuk menemukan waktu untuk bersantai dan merenung hari ini.",
      ],
      pisces: [
        "Jaga kesehatan fisik dan emosional Anda dengan baik hari ini. Perhatikan pola makan dan istirahat yang cukup.",
        "Bersikaplah lembut pada diri sendiri dan orang lain. Kehangatan Anda akan memberi inspirasi pada orang-orang di sekitar Anda.",
        "Kejujuran adalah kunci untuk membangun hubungan yang kokoh. Berbicaralah dari hati.",
        "Anda memiliki intuisi yang kuat. Percayalah pada insting Anda ketika menghadapi keputusan sulit.",
        "Jangan ragu untuk mengekspresikan perasaan Anda secara terbuka kepada orang-orang yang Anda percayai.",
        "Luangkan waktu untuk merenung dan mengevaluasi tujuan hidup Anda hari ini.",
        "Anda memiliki kemampuan untuk memberikan dukungan emosional yang besar pada orang-orang terdekat Anda.",
        "Jangan ragu untuk meminta bantuan atau nasihat dari orang yang Anda percayai saat menghadapi kesulitan.",
        "Jadikan hari ini sebagai kesempatan untuk memaafkan dan melupakan masa lalu yang menyakitkan.",
        "Kesabaran adalah kunci untuk mengatasi tantangan hari ini.",
        "Jangan biarkan emosi negatif menguasai Anda. Cari cara untuk menenangkan pikiran Anda.",
        "Anda memiliki potensi besar. Percayalah pada diri sendiri dan teruslah berusaha.",
        "Berkomitmenlah untuk terus belajar dan berkembang secara pribadi dan profesional.",
        "Perhatikan detail dan jangan abaikan hal-hal kecil yang penting.",
        "Kejujuran adalah pondasi yang kuat untuk membangun hubungan yang langgeng.",
        "Tetap tenang dan teruskan langkah Anda meskipun menghadapi rintangan.",
        "Manfaatkan intuisi Anda dalam mengambil keputusan penting hari ini.",
        "Luangkan waktu untuk bersantai dan mengisi ulang energi.",
        "Jangan ragu untuk mengekspresikan ide-ide kreatif Anda secara terbuka.",
        "Berikan diri Anda penghargaan yang pantas atas pencapaian Anda.",
      ],
      sagittarius: [
        "Hari ini adalah waktu yang tepat untuk mengejar impian besar Anda. Percayalah pada diri sendiri!",
        "Jangan ragu untuk mengambil risiko dalam mencapai tujuan Anda. Keberuntungan sedang berpihak pada Anda.",
        "Manfaatkan energi positif ini untuk menjelajahi hal-hal baru yang dapat meningkatkan pengalaman hidup Anda.",
        "Jadikan hari ini sebagai kesempatan untuk merenungkan arah dan tujuan hidup Anda secara keseluruhan.",
        "Anda memiliki semangat petualang yang besar. Gunakan untuk mengeksplorasi berbagai peluang yang mungkin muncul.",
        "Kejujuran dan integritas akan membawa Anda jauh dalam membangun hubungan yang kokoh.",
        "Bersikaplah fleksibel dalam menghadapi perubahan. Ini adalah kunci untuk berkembang dan beradaptasi.",
        "Jaga keseimbangan antara bekerja keras dan waktu untuk bersantai. Keseimbangan ini penting bagi kesejahteraan Anda.",
        "Anda memiliki kemampuan untuk menginspirasi dan memotivasi orang lain. Gunakanlah dengan bijak.",
        "Jangan biarkan detail kecil menghalangi pandangan Anda pada tujuan besar yang ingin dicapai.",
        "Percayalah pada intuisi Anda dalam mengambil keputusan penting hari ini.",
        "Bersiaplah untuk menghadapi tantangan dengan sikap yang tenang dan percaya diri.",
        "Luangkan waktu untuk merenung dan mengevaluasi kemajuan yang telah Anda capai.",
        "Terimalah tantangan sebagai bagian dari proses belajar dan pertumbuhan pribadi Anda.",
        "Jangan ragu untuk mengejar impian besar Anda. Keberanian Anda akan membawa Anda jauh.",
        "Berikan diri Anda kesempatan untuk berekspresi secara kreatif. Ini akan membantu Anda menemukan solusi baru.",
        "Anda memiliki potensi besar untuk mencapai banyak hal dalam hidup ini. Lanjutkan usaha Anda.",
        "Jangan ragu untuk menunjukkan rasa terima kasih dan apresiasi kepada orang-orang yang Anda cintai.",
        "Jangan biarkan stres mengambil alih. Carilah cara untuk melepaskan dan mengurangi tekanan.",
        "Tetap positif meskipun menghadapi rintangan. Anda memiliki kemampuan untuk mengatasi semuanya."
      ],
      virgo: [
        "Hari ini adalah waktu yang tepat untuk mengevaluasi detail dan merencanakan langkah selanjutnya dengan hati-hati.",
        "Anda memiliki kemampuan analitis yang kuat. Gunakanlah untuk memecahkan masalah yang mungkin muncul hari ini.",
        "Luangkan waktu untuk merawat diri sendiri dan memastikan kesehatan fisik dan mental Anda tetap prima.",
        "Anda memiliki kecenderungan perfeksionis. Ingatlah untuk menerima kelebihan dan kekurangan dengan penuh kasih.",
        "Jadikan hari ini sebagai kesempatan untuk membersihkan dan mengatur lingkungan Anda agar lebih efisien.",
        "Bersiaplah untuk menghadapi tugas-tugas yang membutuhkan perhatian terhadap detail.",
        "Perhatikan komunikasi Anda dengan cermat. Jaga agar tidak ada kebingungan atau salah paham.",
        "Terimalah bahwa tidak semua hal dapat Anda kendalikan. Fokuslah pada hal-hal yang dapat Anda atur.",
        "Gunakan waktu luang Anda untuk belajar hal baru atau mengasah keterampilan yang sudah dimiliki.",
        "Anda memiliki bakat untuk memberikan solusi yang praktis dan efisien dalam situasi yang kompleks.",
        "Jadikan hari ini sebagai kesempatan untuk mendekatkan diri pada orang-orang yang Anda sayangi.",
        "Jangan biarkan kekhawatiran atau keraguan menghambat kemajuan Anda hari ini.",
        "Anda memiliki kemampuan untuk melihat sisi positif dari setiap situasi. Gunakanlah untuk menginspirasi orang lain.",
        "Fokuslah pada tujuan jangka panjang Anda dan lakukan langkah-langkah kecil untuk mencapainya.",
        "Jaga keseimbangan antara ambisi dan realitas. Jadilah realistis dalam menetapkan target.",
        "Penting untuk tetap rendah hati meskipun telah mencapai banyak hal. Teruslah belajar dan berkembang.",
        "Jangan ragu untuk meminta bantuan atau saran dari orang lain. Kolaborasi dapat menghasilkan hasil yang lebih baik.",
        "Jadikan waktu untuk refleksi dan introspeksi. Hal ini akan membantu Anda mendapatkan wawasan baru.",
        "Kejujuran dan integritas adalah kunci untuk membangun hubungan yang kuat dan saling percaya.",
        "Luangkan waktu untuk merenungkan tujuan hidup Anda secara menyeluruh dan buat rencana untuk mencapainya."
      ],
      libra: [
        "Hari ini adalah waktu yang tepat untuk mencari keseimbangan dalam kehidupan pribadi dan profesional Anda.",
        "Anda memiliki kemampuan untuk melihat kedua sisi dari setiap situasi. Gunakanlah untuk mengambil keputusan yang bijaksana.",
        "Jangan ragu untuk mengekspresikan ide-ide kreatif Anda secara terbuka.",
        "Terimalah bahwa konflik adalah bagian dari kehidupan. Fokuslah pada penyelesaian yang adil dan menguntungkan semua pihak.",
        "Gunakan kemampuan diplomasi Anda untuk menyelesaikan masalah atau perselisihan yang mungkin muncul.",
        "Luangkan waktu untuk merenungkan nilai-nilai dan prinsip-prinsip yang Anda pegang teguh.",
        "Anda memiliki bakat untuk mempengaruhi perubahan positif dalam lingkungan Anda. Gunakanlah dengan bijak.",
        "Jadikan hari ini sebagai kesempatan untuk menjalin hubungan yang harmonis dengan orang-orang di sekitar Anda.",
        "Fokuslah pada keseimbangan antara memberikan dan menerima. Ini adalah kunci untuk hubungan yang sehat.",
        "Anda memiliki potensi untuk mencapai kesuksesan besar dalam karier Anda. Lanjutkan usaha Anda.",
        "Kejujuran dan integritas adalah pondasi yang kuat untuk membangun hubungan yang langgeng.",
        "Jaga keseimbangan antara kebutuhan pribadi dan kebutuhan orang lain dalam hidup Anda.",
        "Bersiaplah untuk menghadapi perubahan dengan sikap terbuka dan fleksibel.",
        "Gunakan waktu luang Anda untuk merawat diri sendiri dan mengisi ulang energi.",
        "Jangan ragu untuk mengejar peluang baru yang mungkin muncul hari ini.",
        "Anda memiliki bakat untuk menyampaikan pesan dengan jelas dan persuasif. Manfaatkanlah untuk mempengaruhi orang lain.",
        "Jadikan hari ini sebagai kesempatan untuk menilai kemajuan Anda dalam mencapai tujuan jangka panjang.",
        "Penting untuk menghargai dan menghormati pandangan orang lain. Ini akan memperkuat hubungan Anda.",
        "Tetap fokus pada tujuan Anda meskipun menghadapi gangguan atau tantangan di sepanjang jalan.",
        "Manfaatkan kepekaan emosional Anda untuk memahami perasaan Anda sendiri dan orang lain lebih baik."
      ],
      scorpio: [
        "Hari ini adalah waktu yang tepat untuk merenungkan sisi emosional dalam diri Anda.",
        "Jangan ragu untuk memperdalam hubungan dengan orang-orang terdekat Anda. Ini akan membawa kedekatan yang lebih dalam.",
        "Anda memiliki kemampuan untuk membaca antara baris. Gunakanlah untuk menemukan solusi yang tepat.",
        "Gunakan kekuatan intuisi Anda untuk membuat keputusan yang tepat dalam situasi yang kompleks.",
        "Jadikan hari ini sebagai kesempatan untuk membersihkan dan menyegarkan lingkungan sekitar Anda.",
        "Anda memiliki kemampuan untuk menginspirasi dan mempengaruhi orang lain secara positif.",
        "Terimalah bahwa transformasi adalah bagian alami dari kehidupan. Jadilah fleksibel dalam menghadapinya.",
        "Jaga keseimbangan antara ambisi dan emosi Anda. Ini akan membantu Anda tetap fokus pada tujuan Anda.",
        "Luangkan waktu untuk merenungkan motivasi Anda dalam mengejar tujuan hidup Anda.",
        "Anda memiliki ketajaman analitis yang kuat. Gunakanlah untuk memecahkan masalah yang mungkin muncul hari ini.",
        "Percayalah pada kemampuan Anda untuk mengatasi rintangan yang mungkin muncul dalam perjalanan hidup Anda.",
        "Anda memiliki daya tarik magnetik yang kuat. Gunakanlah untuk menarik hal-hal positif ke dalam hidup Anda.",
        "Jangan biarkan rasa cemburu atau posesif mengganggu hubungan Anda. Berbicaralah secara terbuka dan jujur.",
        "Anda memiliki kemampuan untuk melihat di balik topeng orang lain. Gunakanlah untuk memahami motivasi mereka.",
        "Jadikan hari ini sebagai kesempatan untuk membangun koneksi yang lebih dalam dengan diri Anda sendiri.",
        "Kejujuran dan integritas adalah nilai-nilai yang sangat penting bagi Anda. Pegang teguh prinsip-prinsip itu.",
        "Fokuslah pada hal-hal yang Anda bisa kontrol dan terimalah hal-hal yang tidak bisa Anda ubah.",
        "Anda memiliki daya tarik kepada hal-hal yang misterius dan tersembunyi. Gunakan rasa ingin tahu Anda dengan bijak.",
        "Bersiaplah untuk menyelesaikan tugas-tugas dengan fokus dan ketekunan yang tinggi.",
        "Jangan ragu untuk mengungkapkan perasaan Anda dengan jujur dan terbuka kepada orang-orang yang Anda percayai.",
        "Manfaatkan kemampuan analitis Anda untuk mengenali pola-pola dalam situasi kompleks.",
        "Luangkan waktu untuk merenungkan perubahan yang ingin Anda lakukan dalam hidup Anda."
      ]
  };

  let useLocalStorage = typeof(Storage) !== "undefined";

  function getHoroscope(sign) {
    const signKey = sign.toLowerCase();
    const signHoroscopes = horoscopes[signKey];
    if (!signHoroscopes) {
        return "Zodiak tidak ditemukan.";
    }

    // Ambil tanggal hari ini dalam format yyyy-mm-dd
    const today = new Date().toISOString().split('T')[0];
    
    // Ambil data yang disimpan di localStorage
    const storedDate = localStorage.getItem(signKey + '_date');
    const storedIndex = localStorage.getItem(signKey + '_index');

    let currentIndex;

    // Jika tanggal berubah atau data belum ada, ambil kalimat baru dan perbarui tanggal
    if (storedDate !== today || !storedIndex) {
        currentIndex = Math.floor(Math.random() * signHoroscopes.length);
        localStorage.setItem(signKey + '_date', today);
        localStorage.setItem(signKey + '_index', currentIndex);
    } else {
        currentIndex = parseInt(storedIndex, 10);
    }

    // Dapatkan kalimat ramalan saat ini
    const horoscope = signHoroscopes[currentIndex];

    return horoscope;
}

document.getElementById('horoscopeForm').addEventListener('submit', function (event) {
    event.preventDefault();
    const zodiacSign = document.getElementById('zodiacSign').value;
    const result = getHoroscope(zodiacSign);
    document.getElementById('horoscopeResult').textContent = result;
});
});